import { Programming } from './programming';

export const PROGRAMMING: Programming[] = [
  { id: 11, title: 'HTML', type:'Database Management Application', details: '' },
  { id: 11, title: 'CSS', type:'Database', details: '' },
  { id: 11, title: 'JavaScript', type:'Database Management Application', details: '' },
  { id: 11, title: 'Java', type:'Database Management Application', details: '' },
  { id: 11, title: 'C#', type:'Cloud', details: '' },
  { id: 11, title: 'C', type:'Database Management Application', details: '' },
  { id: 11, title: 'C++', type:'Database Management Application', details: '' },
  { id: 11, title: 'Phython', type:'Database Management Application', details: '' },
  { id: 11, title: 'Phanter', type:'Database Management Application', details: '' },
  { id: 11, title: 'PHP', type:'Database Management Application', details: '' },
  { id: 11, title: 'Cold Fusion', type:'Database Management Application', details: '' },
  { id: 11, title: 'AngularJS', type:'Database Management Application', details: '' },
  { id: 11, title: 'Angular', type:'Database Management Application', details: '' },
  { id: 11, title: 'Polymer', type:'Database Management Application', details: '' },
  { id: 11, title: 'ReactJS', type:'Database Management Application', details: '' },
  { id: 11, title: 'JQuery', type:'Database Management Application', details: '' },
  { id: 11, title: 'JQuery Datatables', type:'Database Management Application', details: '' },
  { id: 11, title: 'Express', type:'Database Management Application', details: '' },
  { id: 11, title: 'TypeScript', type:'Database Management Application', details: '' },
  { id: 11, title: 'Sass', type:'Database Management Application', details: '' },
  { id: 11, title: 'Jasmine', type:'Database Management Application', details: '' },
  { id: 11, title: 'Karma', type:'Database Management Application', details: '' },
  { id: 11, title: 'Protractor', type:'Database Management Application', details: '' },
  { id: 11, title: 'SQL', type:'Database Management Application', details: '' },
  { id: 11, title: 'PL/SQL', type:'Database Management Application', details: '' },
  { id: 11, title: 'Bootstrap', type:'Database Management Application', details: '' },
  { id: 11, title: 'Fusion Charts', type:'Database Management Application', details: '' },
  { id: 11, title: 'Angular Material', type:'Database Management Application', details: '' },
  { id: 11, title: 'P.E.A.R', type:'Database Management Application', details: '' },
  { id: 11, title: 'Animate CSS', type:'Database Management Application', details: '' },
];